### ISSUE TITLE
Erorr with current diffusers (0.22.0.dev0)

### ISSUE THREAD

**Issue by drdsgvo** [SUDO-AI-3D/zero123plus#18]
When running the example code, an error occurs:

...
result = pipeline(cond, num_inference_steps=75).images[0]  # it is Zero123PlusPipeline

Error coming up:
--
  File ".../.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File ".../.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py", line 364, in __call__
    encoder_hidden_states = self._encode_prompt(
  File ".../.local/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 249, in _encode_prompt
    prompt_embeds = torch.cat([prompt_embeds_tuple[1], prompt_embeds_tuple[0]])

TypeError: expected Tensor as element 0 in argument 0, but got NoneType
--

I think this is due to evolved code in diffusers. However, the supported diffusers version (0.20) is sort of outdated. Diffusers is under heavy development and will andvance further. Thus, I kindly ask you for a hint how to fix the code (I could do on my own), or supply the fix.

Thank you

**Comment by profgandhi** [comment]
I am getting same error.

**Comment by profgandhi** [comment]
@drdsgvo try this command
!pip install --no-cache-dir torch==2.1.0 torchvision --index-url https://download.pytorch.org/whl/cu118
to change torch version

**Comment by eliphatfs** [comment]
Thank you for reporting the issue. I think diffusers are making changes to make the methods public (_encode_prompts -> encode_prompts), so you may try that by now. The line with error actually has a comment saying “this is added for backward compatibility” but apparently it didn’t 🤣 
Hopefully I will be able to fix it in 1-2 days.

**Comment by lsongx** [comment]
Just update
```
        encoder_hidden_states = self._encode_prompt(
            prompt,
            self.device,
            num_images_per_prompt,
            False
        )
```
in https://github.com/SUDO-AI-3D/zero123plus/blob/818f325ac6c5aad8a32ccb60158c997f4920afdf/diffusers-support/pipeline.py#L364C1-L364C1 to
```
        encoder_hidden_states = self.encode_prompt(
            prompt,
            self.device,
            num_images_per_prompt,
            False
        )[0]
```

I can submit a PR for this @eliphatfs if you think needed, but that needs the version in requirements to be bumped to 0.22

**Comment by drdsgvo** [comment]
Thank you. That worked!

**Comment by eliphatfs** [comment]
Should have fixed in github, will update the hf pipeline soon after more testing.

**Comment by chengwuxinlin** [comment]
> TypeError: expected Tensor as element 0 in argument 0, but got NoneType

I still have the same issue, could we update the diffusers to fix this? My error is:

```
TypeError                                 Traceback (most recent call last)
[c:\test.ipynb Cell 1 line 2
     [21](vscode-notebook-cell:/test.ipynb#W0sZmlsZQ%3D%3D?line=20) cond = Image.open(requests.get("https://d.skis.ltd/nrp/sample-data/0_cond.png", stream=True).raw)
     [22](vscode-notebook-cell:/test.ipynb#W0sZmlsZQ%3D%3D?line=21) depth = Image.open(requests.get("https://d.skis.ltd/nrp/sample-data/0_depth.png", stream=True).raw)
---> [23](vscode-notebook-cell:test.ipynb#W0sZmlsZQ%3D%3D?line=22) result = pipeline(cond, depth_image=depth, num_inference_steps=100).images[0]
     [24](vscode-notebook-cell:/test.ipynb#W0sZmlsZQ%3D%3D?line=23) result.show()
     [25](vscode-notebook-cell:/test.ipynb#W0sZmlsZQ%3D%3D?line=24) result.save("output.png")

File [c:\Python\Python39\lib\site-packages\torch\utils\_contextlib.py:115](file:///C:Python/Python39/lib/site-packages/torch/utils/_contextlib.py:115), in context_decorator.<locals>.decorate_context(*args, **kwargs)
    [112](file:///Python/Python39/lib/site-packages/torch/utils/_contextlib.py:112) @functools.wraps(func)
    [113](file:///Python/Python39/lib/site-packages/torch/utils/_contextlib.py:113) def decorate_context(*args, **kwargs):
    [114](file:///Python/Python39/lib/site-packages/torch/utils/_contextlib.py:114)     with ctx_factory():
--> [115](file:///Python/Python39/lib/site-packages/torch/utils/_contextlib.py:115)         return func(*args, **kwargs)

File [~\.cache\huggingface\modules\diffusers_modules\local\sudo-ai--zero123plus-pipeline\5006f82f085a8a5e1131440c327cdfde09b9c41a\pipeline.py:364](https://file+.vscode-resource.vscode-cdn.net/c%3A/~/.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py:364), in Zero123PlusPipeline.__call__(self, image, prompt, num_images_per_prompt, guidance_scale, depth_image, output_type, width, height, num_inference_steps, return_dict, *args, **kwargs)
    [361](https://file+.vscode-resource.vscode-cdn.net/c%3A/~/.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py:361) global_embeds = encoded.image_embeds
    [362](https://file+.vscode-resource.vscode-cdn.net/c%3A/~/.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py:362) global_embeds = global_embeds.unsqueeze(-2)
--> [364](https://file+.vscode-resource.vscode-cdn.net/c%3A/~/.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py:364) encoder_hidden_states = self._encode_prompt(
    [365](https://file+.vscode-resource.vscode-cdn.net/c%3A/~/.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py:365)     prompt,
    [366](https://file+.vscode-resource.vscode-cdn.net/c%3A/~/.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py:366)     self.device,
    [367](https://file+.vscode-resource.vscode-cdn.net/c%3A/~/.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py:367)     num_images_per_prompt,
    [368](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/~/.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py:368)     False
    [369](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/~/.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py:369) )
    [370](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/~/.cache/huggingface/modules/diffusers_modules/local/sudo-ai--zero123plus-pipeline/5006f82f085a8a5e1131440c327cdfde09b9c41a/pipeline.py:370) ramp = global_embeds.new_tensor(self.config.ramping_coefficients).unsqueeze(-1)
...
    [250](file:///Python/Python39/lib/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py:250) # concatenate for backwards comp
--> [251](file:///Python/Python39/lib/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py:251) prompt_embeds = torch.cat([prompt_embeds_tuple[1], prompt_embeds_tuple[0]])
    [253](file:///Python/Python39/lib/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py:253) return prompt_embeds

TypeError: expected Tensor as element 0 in argument 0, but got NoneType
```

**Comment by eliphatfs** [comment]
I have updated the HF pipeline. Please comment if you still have issues.
